CREATE DATABASE bloco-de-produtos;

CREATE TABLE PRODUTOS
(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    VALOR DECIMAL(5,10) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    CATEGORIA CHAR(1) NOT NULL,
)ENGINE=InnoDB;

CREATE TABLE CATEGORIA
(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CATEGORIA VARCHAR(255)
)ENGINE=InnoDB;